# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_myname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myname',
            name='good',
            field=models.BooleanField(verbose_name='false'),
        ),
    ]
